### PR TITLE
(feat):Adding product repository and test

### PR DESCRIPTION
**Pull request by Aryevang**
Adding the repository to manage the product persistence and the corresponde unit test file.

### CODE REVIEW

**Review by reynoldmorel — CHANGES_REQUESTED** [review]
Why are you uysing task async?

**Comment by Aryevang** [comment]
> Why are you uysing task async?

@reynoldmorel , When we'll be using another persistence system like a database, is very likely that the methods exposed from the api used to communicate with it are async, so I expect to use this same interfaces.

**Comment by reynoldmorel** [comment]
> > Why are you uysing task async?
> 
> @reynoldmorel , When we'll be using another persistence system like a database, is very likely that the methods exposed from the api used to communicate with it are async, so I expect to use this same interfaces.

The thing is that we don't need it now, could we keep it simple?

**Comment by Aryevang** [comment]
> > > Why are you uysing task async?
> > 
> > 
> > @reynoldmorel , When we'll be using another persistence system like a database, is very likely that the methods exposed from the api used to communicate with it are async, so I expect to use this same interfaces.
> 
> The thing is that we don't need it now, could we keep it simple?

Ok. I'll make the change and let you know when is ready.

**Comment by Aryevang** [comment]
@reynoldmorel , changes applied based on recommendation.

**Review by reynoldmorel — APPROVED** [review]

**Pull request merged**
